version: '3.7'

services:
  pg:
    image: bitnami/postgresql:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
    volumes:
      - pg-next-saas:/var/lib/postgresql/data

volumes:
  pg-next-saas:
